
import jsPDF from 'jspdf';

interface AnalysisResult {
  energizers: string[];
  avoid: string[];
  environments: string[];
  growth: string[];
}

interface DeepDiveData {
  winNumber: number;
  process: string;
}

export const generateSEEDProfilePDF = (
  analysis: AnalysisResult,
  deepDiveData: DeepDiveData[],
  isPremium: boolean = false
) => {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageHeight = pdf.internal.pageSize.height;
  const margin = 20;
  const maxWidth = pdf.internal.pageSize.width - 2 * margin;

  // Helper function to add text with line wrapping
  const addWrappedText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) {
      pdf.setFont(undefined, 'bold');
    } else {
      pdf.setFont(undefined, 'normal');
    }
    
    const lines = pdf.splitTextToSize(text, maxWidth);
    
    // Check if we need a new page
    if (yPosition + (lines.length * fontSize * 0.35) > pageHeight - margin) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.35 + 10;
  };

  // Title Page
  pdf.setFontSize(24);
  pdf.setFont(undefined, 'bold');
  pdf.text('SEED Profile Analysis', margin, yPosition);
  yPosition += 30;

  pdf.setFontSize(16);
  pdf.setFont(undefined, 'normal');
  pdf.text(isPremium ? 'Premium Report' : 'Free Report', margin, yPosition);
  yPosition += 20;

  pdf.setFontSize(12);
  pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 30;

  // What Energizes You
  addWrappedText('🧠 WHAT ENERGIZES YOU', 16, true);
  analysis.energizers.forEach((item, index) => {
    addWrappedText(`${index + 1}. ${item}`, 12);
  });
  yPosition += 10;

  // What to Avoid
  addWrappedText('🚫 WHAT TO AVOID', 16, true);
  analysis.avoid.forEach((item, index) => {
    addWrappedText(`${index + 1}. ${item}`, 12);
  });
  yPosition += 10;

  // Ideal Environments
  addWrappedText('🏞️ IDEAL WORK & CONTRIBUTION ENVIRONMENTS', 16, true);
  analysis.environments.forEach((item, index) => {
    addWrappedText(`${index + 1}. ${item}`, 12);
  });
  yPosition += 10;

  // Growth Opportunities
  addWrappedText('🌱 GROWTH OPPORTUNITIES', 16, true);
  analysis.growth.forEach((item, index) => {
    addWrappedText(`${index + 1}. ${item}`, 12);
  });

  if (isPremium) {
    // Add premium content sections
    pdf.addPage();
    yPosition = 20;
    
    addWrappedText('PREMIUM ANALYSIS SECTIONS', 18, true);
    addWrappedText('This premium analysis includes expanded insights based on your detailed process descriptions and SIMA methodology.', 12);
    
    // Core Motivational DNA
    addWrappedText('🧬 CORE MOTIVATIONAL DNA', 16, true);
    addWrappedText('Your motivational core is built around systematic execution and vision realization. You are energized by taking complex ideas and breaking them down into actionable steps that lead to tangible outcomes.', 12);
    
    // Decision-Making Style
    addWrappedText('🧠 DECISION-MAKING STYLE', 16, true);
    addWrappedText('You approach decisions through methodical analysis, preferring to research thoroughly before committing. Your decisions are typically data-driven but also consider long-term strategic implications.', 12);
    
    // Add more premium sections...
  }

  // Footer
  pdf.setFontSize(10);
  pdf.setFont(undefined, 'italic');
  pdf.text('Generated by SEED Profile Analysis Tool', margin, pageHeight - 15);

  return pdf;
};
